### ISSUE TITLE
Possible entries missing in reference motion

### ISSUE THREAD

**Issue by quantumiracle** [facebookresearch/TCDM#1]
Hi, 

Thanks for your great work!
However, when I'm trying to generate a trajectory for the object (not including the hand), I found that it requires to set the qpos and qvel of the object. But in the code [here](https://github.com/facebookresearch/TCDM/blob/beda9f25af5b48d106d1adf4b51eac2829f5830a/tcdm/envs/reference.py#L52), it seems the entries `s` is missing in the reference motion, and also for the others like `sdot`, `eef_pos`, etc. I'm wondering if it's not provided or actually not existing in the data at the beginning.

Thanks

**Comment by SudeepDasari** [comment]
Hi @quantumiracle, thanks for your interest in our code!

Sorry for the confusion regarding the missing entries. We chose to limit our release right now to the pre-grasp information and object trajectories. This is because: (1) our paper's framework doesn't use the additional information (only baselines needed them), and (2) there were some unclear licensing issues with releasing trajectories from the [GRAB dataset](https://grab.is.tue.mpg.de/) as part of our code. 

If you're interested in that data, I would encourage you to download GRAB yourself and process them into our trajectory format.
